apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "AppCtxWithEnv.name" . }}-db
spec:
  storageClassName: gp2
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.db.storageSize }}