apiVersion: v1
kind: Service
metadata:
  name: {{ template "AppCtxWithEnv.name" . }}-db
spec:
  selector:
    app: {{ template "dbSelector.name" . }}
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432