{{- if .Values.front.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "AppCtxWithEnv.name" . }}-front
spec:
  selector:
    app: {{ template "frontSelector.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
{{- end }}