apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "AppCtxWithEnv.name" . }}-api
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.api.ingress.prefix }}.{{ .Values.env }}.{{ .Values.url_suffix }}
      http:
        paths:
          - backend:
              service:
                name: {{ template "AppCtxWithEnv.name" . }}-api
                port:
                  number: 8080
            path: /
            pathType: Prefix
{{- if .Values.api.ingress.tlsEnabled }}
  tls:
  - hosts:
      - {{ .Values.api.ingress.prefix }}.{{ .Values.env }}.{{ .Values.url_suffix }}
    secretName: app-wildcard
{{- end }}