apiVersion: v1
kind: Service
metadata:
  name: {{ template "AppCtxWithEnv.name" . }}-api
spec:
  selector:
    app: {{ template "apiSelector.name" . }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080